// Code generated by go run ./native/cmd/matrix-ts-types; DO NOT EDIT.

export interface MatrixCoreInitOptions {
  accessToken: string;
  catchUpOnStart?: boolean;
  deviceId?: string;
  homeserverUrl: string;
  initialSyncMode?: "persisted" | "latest" | "catch_up";
  initialSyncSince?: string;
  pickleKey?: string;
  recoveryCode?: string;
  recoveryKey?: string;
  userId?: string;
  verifyRecoveryOnStart?: boolean;
}

export interface MatrixWhoami {
  userId: string;
  deviceId: string;
}

export interface MatrixUploadMediaOptions {
  bytesBase64: string;
  contentType?: string;
  filename?: string;
}

export interface MatrixSendMediaMessageOptions {
  roomId: string;
  body?: string;
  bytesBase64: string;
  contentType?: string;
  duration?: number;
  filename?: string;
  height?: number;
  msgtype?: "m.image" | "m.video" | "m.audio" | "m.file";
  size?: number;
  threadRootEventId?: string;
  width?: number;
}

export interface MatrixDownloadMediaOptions {
  contentUri: string;
}

export interface MatrixEncryptedFile {
  hashes: { sha256: string };
  iv: string;
  key: MatrixEncryptedFileKey;
  url: string;
  v: "v2";
}

export interface MatrixEncryptedFileKey {
  alg: "A256CTR";
  ext: true;
  k: string;
  key_ops: ["encrypt", "decrypt"];
  kty: "oct";
}

export interface MatrixDownloadEncryptedMediaOptions {
  file: MatrixEncryptedFile;
}

export interface MatrixSendMessageOptions {
  roomId: string;
  body: string;
  content?: Record<string, unknown>;
  formattedBody?: string;
  mentions?: MatrixMentions;
  msgtype?: "m.text" | "m.notice" | "m.emote";
  threadRootEventId?: string;
  replyToEventId?: string;
}

export interface MatrixMentions {
  room?: boolean;
  userIds?: string[];
}

export interface MatrixRawMessage {
  eventId: string;
  roomId: string;
  raw: unknown;
}

export interface MatrixCreateBeeperStreamResult {
  descriptor: Record<string, unknown>;
}

export interface MatrixCreateBeeperStreamOptions {
  roomId: string;
  streamType?: string;
}

export interface MatrixBeeperStreamOptions {
  content?: Record<string, unknown>;
  eventId: string;
  roomId: string;
}

export interface MatrixRegisterBeeperStreamOptions {
  descriptor: Record<string, unknown>;
  eventId: string;
  roomId: string;
}

export interface MatrixEditMessageOptions {
  roomId: string;
  messageId: string;
  body: string;
  content?: Record<string, unknown>;
  formattedBody?: string;
  mentions?: MatrixMentions;
  msgtype?: "m.text" | "m.notice" | "m.emote";
}

export interface MatrixSendEphemeralEventOptions {
  content: Record<string, unknown>;
  eventType: string;
  roomId: string;
  transactionId?: string;
}

export interface MatrixDeleteMessageOptions {
  roomId: string;
  messageId: string;
  reason?: string;
}

export interface MatrixTypingOptions {
  roomId: string;
  typing: boolean;
  timeoutMs?: number;
}

export interface MatrixFetchMessageOptions {
  roomId: string;
  messageId: string;
}

export interface MatrixFetchMessagesOptions {
  roomId: string;
  cursor?: string;
  direction?: "backward" | "forward";
  limit?: number;
  threadRootEventId?: string;
}

export interface MatrixMarkReadOptions {
  eventId: string;
  roomId: string;
}

export interface MatrixReactionOptions {
  roomId: string;
  messageId: string;
  emoji: string;
}

export interface MatrixFetchRoomOptions {
  roomId: string;
}

export interface MatrixRoomInfo {
  encrypted: boolean;
  id: string;
  isDM?: boolean;
  joinRule?: string;
  memberCount?: number;
  name?: string;
  topic?: string;
  raw?: Record<string, unknown>;
  visibility?: "private" | "workspace" | "external" | "unknown";
}

export interface MatrixOpenDMOptions {
  userId: string;
}

export interface MatrixJoinRoomOptions {
  roomIdOrAlias: string;
}

export interface MatrixLeaveRoomOptions {
  reason?: string;
  roomId: string;
}

export interface MatrixInviteUserOptions {
  reason?: string;
  roomId: string;
  userId: string;
}

export interface MatrixSyncOnceOptions {
  timeoutMs?: number;
}

export interface MatrixSyncStartOptions {
  retryDelayMs?: number;
  timeoutMs?: number;
}

export interface MatrixApplySyncResponseOptions {
  since?: string;
  response: unknown;
}

export interface MatrixListRoomThreadsOptions {
  cursor?: string;
  limit?: number;
  roomId: string;
}

export interface MatrixRawEvent {
  content: Record<string, unknown>;
  eventId: string;
  isMe?: boolean;
  originServerTs?: number;
  raw: unknown;
  roomId: string;
  sender: string;
  type: string;
}

export interface MatrixMediaInfo {
  contentType?: string;
  duration?: number;
  height?: number;
  size?: number;
  width?: number;
}

export interface MatrixMediaAttachment {
  contentUri?: string;
  encryptedFile?: MatrixEncryptedFile;
  filename?: string;
  info?: MatrixMediaInfo;
  msgtype: "m.image" | "m.video" | "m.audio" | "m.file";
}

export interface MatrixMessageEvent extends MatrixRawEvent {
  attachments?: MatrixMediaAttachment[];
  body: string;
  formattedBody?: string;
  isEncrypted?: boolean;
  isEdited?: boolean;
  msgtype: string;
  threadRootEventId?: string;
}

export interface MatrixReactionEvent extends MatrixRawEvent {
  added?: boolean;
  key: string;
  relatesToEventId: string;
}

export interface MatrixInviteEvent {
  inviter?: string;
  raw: unknown;
  roomId: string;
}

export interface MatrixRoomThreadSummary {
  lastReplyTs?: number;
  replyCount?: number;
  root: MatrixMessageEvent;
}

export interface MatrixFetchMessagesResult {
  messages: MatrixMessageEvent[];
  nextCursor?: string;
}

export interface MatrixFetchMessageResult {
  message?: MatrixMessageEvent | null;
}

export interface MatrixUploadMediaResult {
  contentUri: string;
  raw: unknown;
}

export interface MatrixDownloadMediaResult {
  bytesBase64: string;
}

export interface MatrixUploadEncryptedMediaResult {
  contentUri: string;
  file: MatrixEncryptedFile;
  raw: unknown;
}

export interface MatrixOpenDMResult {
  raw: unknown;
  roomId: string;
}

export interface MatrixJoinRoomResult {
  raw: unknown;
  roomId: string;
}

export interface MatrixJoinedRoomsResult {
  raw: unknown;
  roomIds: string[];
}

export interface MatrixUserInfo {
  avatarUrl?: string;
  displayName?: string;
  raw: unknown;
  userId: string;
}

export interface MatrixListRoomThreadsResult {
  nextCursor?: string;
  threads: MatrixRoomThreadSummary[];
}

export interface MatrixGetUserOptions {
  userId: string;
}

