// Code generated by go run ./native/cmd/matrix-ts-types; DO NOT EDIT.

export interface MatrixRawEvent {
  content: Record<string, unknown>;
  eventId: string;
  isMe?: boolean;
  originServerTs?: number;
  raw: unknown;
  roomId: string;
  sender: string;
  type: string;
}

export interface MatrixMentions {
  room?: boolean;
  userIds?: string[];
}

export interface MatrixMediaInfo {
  contentType?: string;
  duration?: number;
  height?: number;
  size?: number;
  width?: number;
}

export interface MatrixEncryptedFileKey {
  alg: "A256CTR";
  ext: true;
  k: string;
  key_ops: ["encrypt", "decrypt"];
  kty: "oct";
}

export interface MatrixEncryptedFile {
  hashes: { sha256: string };
  iv: string;
  key: MatrixEncryptedFileKey;
  url: string;
  v: "v2";
}

export interface MatrixMediaAttachment {
  contentUri?: string;
  encryptedFile?: MatrixEncryptedFile;
  filename?: string;
  info?: MatrixMediaInfo;
  msgtype: "m.image" | "m.video" | "m.audio" | "m.file";
}

export interface MatrixMessageEvent extends MatrixRawEvent {
  attachments?: MatrixMediaAttachment[];
  body: string;
  formattedBody?: string;
  isEncrypted?: boolean;
  isEdited?: boolean;
  msgtype: string;
  threadRootEventId?: string;
}

export interface MatrixReactionEvent extends MatrixRawEvent {
  added?: boolean;
  key: string;
  relatesToEventId: string;
}

export interface MatrixInviteEvent {
  inviter?: string;
  raw: unknown;
  roomId: string;
}

export interface MatrixRoomThreadSummary {
  lastReplyTs?: number;
  replyCount?: number;
  root: MatrixMessageEvent;
}

