package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
)

func main() {
	root := filepath.Join("internal", "core")
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, root, nil, parser.ParseComments)
	check(err)

	var out bytes.Buffer
	out.WriteString("// Code generated by go run ./native/cmd/matrix-ts-types; DO NOT EDIT.\n\n")
	pkgNames := make([]string, 0, len(pkgs))
	for name := range pkgs {
		pkgNames = append(pkgNames, name)
	}
	sort.Strings(pkgNames)
	for _, pkgName := range pkgNames {
		pkg := pkgs[pkgName]
		fileNames := make([]string, 0, len(pkg.Files))
		for name := range pkg.Files {
			fileNames = append(fileNames, name)
		}
		sort.Strings(fileNames)
		for _, fileName := range fileNames {
			file := pkg.Files[fileName]
			for _, decl := range file.Decls {
				gen, ok := decl.(*ast.GenDecl)
				if !ok || gen.Tok != token.TYPE || gen.Doc == nil {
					continue
				}
				name, ok := exportName(gen.Doc.Text())
				if !ok {
					continue
				}
				spec, ok := gen.Specs[0].(*ast.TypeSpec)
				if !ok {
					continue
				}
				st, ok := spec.Type.(*ast.StructType)
				if !ok {
					continue
				}
				writeInterface(&out, name, st)
			}
		}
	}
	check(os.WriteFile(filepath.Join("..", "src", "generated-runtime-types.ts"), out.Bytes(), 0o644))
}

func exportName(doc string) (string, bool) {
	for _, line := range strings.Split(doc, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "ts:export ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "ts:export ")), true
		}
	}
	return "", false
}

func writeInterface(out *bytes.Buffer, name string, st *ast.StructType) {
	fmt.Fprintf(out, "export interface %s", name)
	if len(st.Fields.List) > 0 && len(st.Fields.List[0].Names) == 0 {
		fmt.Fprintf(out, " extends %s", tsType(st.Fields.List[0].Type, ""))
		st.Fields.List = st.Fields.List[1:]
	}
	out.WriteString(" {\n")
	for _, field := range st.Fields.List {
		if len(field.Names) == 0 {
			continue
		}
		tag := tagValue(field.Tag)
		jsonName, optional := jsonField(tag, field.Names[0].Name)
		if jsonName == "-" {
			continue
		}
		override := reflect.StructTag(tag).Get("ts")
		fmt.Fprintf(out, "  %s%s: %s;\n", jsonName, optionalMark(optional, field.Type), tsType(field.Type, override))
	}
	out.WriteString("}\n\n")
}

func optionalMark(tagOptional bool, expr ast.Expr) string {
	if star, ok := expr.(*ast.StarExpr); ok {
		if strings.Contains(tsType(star.X, ""), " | null") {
			return ""
		}
	}
	if tagOptional {
		return "?"
	}
	if _, ok := expr.(*ast.StarExpr); ok {
		return "?"
	}
	return ""
}

func jsonField(tag, fallback string) (string, bool) {
	value := reflect.StructTag(tag).Get("json")
	if value == "" {
		return strings.ToLower(fallback[:1]) + fallback[1:], false
	}
	parts := strings.Split(value, ",")
	return parts[0], len(parts) > 1 && parts[1] == "omitempty"
}

func tagValue(lit *ast.BasicLit) string {
	if lit == nil {
		return ""
	}
	return strings.Trim(lit.Value, "`")
}

func tsType(expr ast.Expr, override string) string {
	if override != "" {
		return override
	}
	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "string":
			return "string"
		case "bool":
			return "boolean"
		case "int", "int64", "uint":
			return "number"
		case "any":
			return "unknown"
		case "OutboundEvent":
			return "Record<string, unknown>"
		case "encryptedFile":
			return "MatrixEncryptedFile"
		case "encryptedFileKey":
			return "MatrixEncryptedFileKey"
		case "mentionsReq":
			return "MatrixMentions"
		default:
			if strings.HasPrefix(t.Name, "ts") {
				name := strings.TrimPrefix(t.Name, "ts")
				return "Matrix" + strings.ToUpper(name[:1]) + name[1:]
			}
			return t.Name
		}
	case *ast.StarExpr:
		return tsType(t.X, "")
	case *ast.ArrayType:
		return tsType(t.Elt, "") + "[]"
	case *ast.MapType:
		return "Record<" + tsType(t.Key, "") + ", " + tsType(t.Value, "") + ">"
	case *ast.SelectorExpr:
		if x, ok := t.X.(*ast.Ident); ok && x.Name == "json" && t.Sel.Name == "RawMessage" {
			return "unknown"
		}
	}
	return "unknown"
}

func check(err error) {
	if err != nil {
		panic(err)
	}
}
